### ISSUE TITLE
On Window GCP numbers have "??" appended

### ISSUE THREAD

**Issue by mleotta** [Kitware/TeleSculptor#477]

**Comment by mwoehlke-kitware** [comment]
Oh, joy… is this sentence *also* full of `?`s?

**Comment by mleotta** [comment]
I'm not sure what you are asking?  Are you asking if this issue shows up in Github comments?

**Comment by mwoehlke-kitware** [comment]
I'm trying to determine if the problem is a lousy Windows font that lacks those code points ([2004](http://www.unicode-symbol.com/u/2004.html) and [2007](http://www.unicode-symbol.com/u/2007.html)), or if the compiler botched the string literal. Can you try copy/pasting those into a GCP name?

(I'm trying to use a space that is the same width as a ')'. For me, [0020](http://www.unicode-symbol.com/u/0020.html) is too narrow. I think 2007 is a bit wide, though, and maybe 2004 shows up?)

**Comment by mleotta** [comment]
`\u2003`, `\u2004`, and `\u2007` all show up as `?`.  `\u0020` makes a space.

**Comment by mwoehlke-kitware** [comment]
Wow... trash fonts on Windows, once again... sigh.
