### ISSUE TITLE
TeleSculptor-1.1.2-Darwin-x86_64.dmg

### ISSUE THREAD

**Issue by alicera** [Kitware/TeleSculptor#502]
https://github.com/Kitware/TeleSculptor/releases/tag/v1.1.2
I would like build TeleSculptor binary with macos. How can I do?

**Comment by russelldj** [comment]
I'm not sure what you mean by building "with macros". If you are just trying to build from source, perhaps with the configurable CMake options, please download the source code from the link you provided and then follow the documentation for [Building Telesculptor](https://github.com/Kitware/TeleSculptor#building-telesculptor). Note that you will follow the option based on extracting the zip file from the latest release, rather than using git to get the most recent version of the code.

**Comment by mleotta** [comment]
Sorry for the slow response.  I think the question was referring to "MacOS" (ie Apple), but that does look an awful lot like "macros" at first glance.   We do have a DMG binary package for MacOS so you can run the software without building it.  However, the MacOS build is currently limited in that it can't run the CUDA algorithms (depth map fusion) since Apple devices haven't shipped with NVidia GPUs for the last several years.  We have a CPU alternative for depth map fusion that should be available in the upcoming release.

If you want to build from source you can follow the instructions as @russelldj pointed out and then ask specific questions if you into trouble.
